package db;
// Generated 03.03.2015 11:57:35 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Entities generated by hbm2java
 */
public class Entities  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    
     private long id;
     private String content;
     private String created;

    public Entities() {
    }
    public Entities(Entities ent){
        this.id=0L;
        this.content=ent.content;
        this.created=ent.created;
    }
	
    
    public Entities(long id, String content, String created) {
       this.id=0L;
       this.content = content;
       this.created=created;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = 0L;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getCreated() {
        return this.created;
    }
    
    public void setCreated(String created) {
        this.created=created;
    }
    public boolean isEmpty(){
    return content==null || created==null || content.isEmpty() || created.isEmpty();
}
    public String getSQLstring(){
    return "insert into entities (content, created) values('" +
            content + "','" + created + "')";
}


}


