package db;
// Generated 03.03.2015 11:57:35 by Hibernate Tools 4.3.1



/**
 * Config generated by hbm2java
 */
public class SrvConfig  implements java.io.Serializable {


     private long id;
     private String source;
     private String destination;
     private Integer delay;
     private String wrong;

    public SrvConfig() {
        id=1L;
    }

	
    public SrvConfig(long id) {
        this.id = id;
    }
    public SrvConfig(long id, String source, String destination, Integer delay, String wrong) {
       this.id = id;
       this.source = source;
       this.destination = destination;
       this.delay = delay;
       this.wrong = wrong;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public Integer getDelay() {
        return this.delay;
    }
    
    public void setDelay(Integer delay) {
        this.delay = delay;
    }
    public String getWrong() {
        return this.wrong;
    }
    
    public void setWrong(String wrong) {
        this.wrong = wrong;
    }
    public void setParameters(long id, String source, String destination, Integer delay, String wrong) {
       
       this.source = source;
       this.destination = destination;
       this.delay = delay;
       this.wrong = wrong;
    }
    public boolean notSet(){
        return this.wrong==null | this.source==null | this.destination==null | this.delay==0;
     
    }



}


